# Generated by Django 5.0.6 on 2024-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('numero_cuenta', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField()),
                ('moroso', models.BooleanField(default=False)),
            ],
        ),
    ]
