# Generated by Django 5.0.6 on 2024-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
