# Generated by Django 5.0.6 on 2024-06-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0002_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=40)),
                ('servicio_solucion', models.CharField(max_length=50)),
            ],
        ),
    ]
