# Generated by Django 5.0.6 on 2024-06-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0006_alter_agente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='departamento',
            field=models.CharField(choices=[('Atencion al cliente', 'Atencion al cliente'), ('Soporte Tecnico', 'Soporte Tecnico'), ('Ventas', 'Ventas'), ('Desarrollo de productos', 'Desarrollo de productos'), ('Administracion de redes', 'Administracion de redes')], max_length=140),
        ),
    ]
