# Generated by Django 5.0.6 on 2024-06-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0008_area_rename_servicio_serviciocliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='nethelp.area')),
            ],
        ),
    ]
