# Generated by Django 5.0.6 on 2024-06-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0009_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subservicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicios', to='nethelp.servicio')),
            ],
        ),
    ]
