# Generated by Django 5.0.6 on 2024-06-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0010_subservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('Vencido', 'Vencido')], max_length=20)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('asignacion_actual', models.CharField(choices=[('Administracion de redes', 'Administracion de redes'), ('Soporte en campo', 'Soporte en campo'), ('Ventas', 'Ventas'), ('Soporte Tecnico', 'Soporte Tecnico'), ('Atencion al cliente', 'Atencion al cliente')], default='Atencion al cliente', max_length=100)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_agente', to='nethelp.agente')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_cliente', to='nethelp.usuario')),
                ('nombre_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nethelp.area')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nethelp.servicio')),
                ('sub_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nethelp.subservicio')),
            ],
        ),
    ]
