# Generated by Django 5.0.6 on 2024-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0011_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioDisponible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ServicioCliente',
        ),
    ]
