# Generated by Django 5.0.6 on 2024-06-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0012_serviciodisponible_delete_serviciocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('vencido', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_contratados', to='nethelp.usuario')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nethelp.serviciodisponible')),
            ],
        ),
    ]
