# Generated by Django 5.0.6 on 2024-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0014_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='password',
            field=models.CharField(default='blujunior2725', max_length=120),
        ),
    ]
