# Generated by Django 5.0.6 on 2024-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0016_alter_agente_options_alter_agente_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
