# Generated by Django 5.0.6 on 2024-07-03 17:36

import nethelp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0017_alter_agente_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agente',
            managers=[
                ('objects', nethelp.models.AgenteManager()),
            ],
        ),
    ]
