# Generated by Django 5.0.6 on 2024-07-04 01:08

import nethelp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0018_alter_agente_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', nethelp.managers.UsuarioManager()),
            ],
        ),
    ]
