# Generated by Django 5.0.6 on 2024-07-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0019_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
