# Generated by Django 5.0.6 on 2024-07-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nethelp', '0020_alter_agente_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
